"""Create rooms table

Revision ID: 788c65b16a43
Revises: 42e758f70f35
Create Date: 2025-08-01 18:57:30.640369

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "788c65b16a43"
down_revision: str | Sequence[str] | None = "42e758f70f35"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("rooms",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("hotel_id", sa.Integer(), nullable=False),
    sa.Column("title", sa.String(), nullable=False),
    sa.Column("description", sa.String(), nullable=True),
    sa.Column("price", sa.Integer(), nullable=False),
    sa.Column("quantity", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["hotel_id"], ["hotels.id"] ),
    sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rooms")
    # ### end Alembic commands ###
